### PR TITLE
OpenMP support to bk-tree find_batch

### PR DESCRIPTION
**Pull request by Dobatymo**
move ENABLE_OMP_PARALLEL define to setup.py

@pablocael do we need to add the macro definition somewhere for the cpp tests?

### CODE REVIEW

**Comment by pablocael** [comment]
> move ENABLE_OMP_PARALLEL define to setup.py
> 
> @pablocael do we need to add the macro definition somewhere for the cpp tests?

Sorry for the late reply. Im adding a macro definition here: https://github.com/pablocael/pynear/blob/main/pynear/include/VPTree.hpp#L25 on VPTree.hpp, but I dont think its a good idea to define the macro in the hpp. I think its indeed better to add the macro in the CMakelists.txt if you can do that would be a good improvement. Thank you!

**Review by pablocael — APPROVED** [review]
LGTM!
:+1: 
:bow:

**Comment by Dobatymo** [comment]
@pablocael can you check the latest commit and see if the define in cmakelists is ok? I don't know much about cmake.

**Comment by pablocael** [comment]
> @pablocael can you check the latest commit and see if the define in cmakelists is ok? I don't know much about cmake.



> @pablocael can you check the latest commit and see if the define in cmakelists is ok? I don't know much about cmake.

It seems to be correct! :+1: 
LGTM

**Pull request merged**
